version: 0.7.{build}
skip_tags: true
image:
  - Visual Studio 2019
  - Ubuntu2004
configuration: Release
platform: x64
environment:
  CC: /usr/bin/gcc-9
  CXX: /usr/bin/g++-9
install:
  - sh: sudo apt-get -y install libgl1-mesa-dev
before_build:
  - mkdir build
  - cd build
  - cmd: cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_PREFIX_PATH=C:\Qt\6.0.0\msvc2019_64 ..
  - sh: cmake -DCMAKE_PREFIX_PATH=$HOME/Qt/6.0.0/gcc_64 ..
build_script:
  - cmake --build . --config Release
